Skip formatting of empty code block
In case we are formatting an empty block, the code will be
simplified (e.g removing unnecessary newline characters) so in this
case we need to not try to extract the inexisting inner
code block.

Fixes: #3054

,----[ Backtrace of panic - #3054 issue ]
| thread 'main' panicked at 'begin <= end (12 <= 11) when slicing `fn main() {}
| `', libcore/str/mod.rs:2098:5
| stack backtrace:
|    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
|              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
|    1: std::sys_common::backtrace::print
|              at libstd/sys_common/backtrace.rs:71
|              at libstd/sys_common/backtrace.rs:59
|    2: std::panicking::default_hook::{{closure}}
|              at libstd/panicking.rs:211
|    3: std::panicking::default_hook
|              at libstd/panicking.rs:227
|    4: std::panicking::rust_panic_with_hook
|              at libstd/panicking.rs:477
|    5: std::panicking::continue_panic_fmt
|              at libstd/panicking.rs:391
|    6: rust_begin_unwind
|              at libstd/panicking.rs:326
|    7: core::panicking::panic_fmt
|              at libcore/panicking.rs:77
|    8: core::str::slice_error_fail
|              at libcore/str/mod.rs:0
|    9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
|   10: rustfmt_nightly::format_code_block
`----

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>